services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python /app/main.py'
    ports:
      - 8001:5000
    volumes:
      - .:/app/
    depends_on:
      - db

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python /app/consumer.py'
    volumes:
      - .:/app/
    depends_on:
      - db

  db:
    image: mysql:8.0.32
    restart: always
    environment:
      MYSQL_DATABASE: main   
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3307:3306
    volumes:
      - ./.mysql-data/main:/var/lib/mysql
